spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: pedido-service
              uri: lb://pedido-service
              predicates:
                - Path=/pedido/**

            - id: inventario-service
              uri: lb://inventario-service
              predicates:
                - Path=/inventario/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      enabled: true

server:
  port: 8080