spring:
  application:
    name: pedido-service

  datasource:
    url: jdbc:postgresql://postgres-pedido:5432/pedidos
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:29092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

server:
    port: 8001